# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'sftp'
            options:
               host: '%env(SFTP_HOST)%'
               port: '%env(int:SFTP_PORT)%'
               username: '%env(SFTP_USER)%'
               password: '%env(SFTP_PASS)%'
               timeout: 5
 
